### PR TITLE
fix: discover standalone Codex subagents

### PR DESCRIPTION
**Pull request by levin7734**
## Summary

- classify Codex rollouts as child sessions only when explicit parent metadata exists
- catalog `source.subagent` rollouts without a parent as standalone sessions
- reclassify stale v4 subagent cache entries without rereading cached roots
- add discovery and hydration regressions while preserving linked-child behavior

## Why

Codex can emit standalone reviewer or guardian rollouts with
`source.subagent` but without `payload.session_id` or
`payload.parent_thread_id`. Discovery currently treats every such rollout as a
child, so it creates no catalog row and targeted hydration fails with
`SESSION_NOT_FOUND` unless another selected root links to it.

On a bounded 11-file Codex sample, published `0.11.0` discovered 6 roots and
hydrated 10 provider IDs. The omitted standalone guardian was present as a
discovery candidate but could not be hydrated directly.

This change keeps `thread_source: "subagent"` and subagents with an explicit
parent classified as children. Only an unlinked `source.subagent` rollout is
cataloged under its own provider ID.

## Validation

- current upstream base: `7b3666f64f90d26baab67a0d2b56276d10d9dd27`
- Rust engine: 222 tests pass, 0 fail, and the declared performance benchmark
  is the only ignored test (200 library, 19 discovery, 3 resilience)
- TypeScript SDK: 23/23 tests pass
- bounded sample: 7 catalog sessions, all 11 provider IDs, 2,727 events, 30
  prompts, 1,343 tool calls, and 4 existing child relations
- repeat hydration: 7/7 `unchanged`
- full-text checks: 3/3 distinctive prompts resolve to the expected sessions,
  including the standalone guardian

No database schema or public SDK contract changes.

---

> [!NOTE]
> **Medium Risk**
> Changes session classification, discovery stamps, and Codex sync state migration; incorrect logic could miscatalog subagents or skip re-ingestion, but scope is Codex-specific with extensive regression tests.
> 
> **Overview**
> **Standalone Codex guardian rollouts** (`source.subagent` without parent metadata) are now cataloged and hydrated as root sessions instead of being treated like linked subagents.
> 
> Classification is centralized in **`codex_is_subagent`**: a rollout is a child only when `thread_source: "subagent"` or when `source.subagent` is present **and** an explicit parent can be resolved. Shallow discovery bumps **`SHALLOW_SCANNER_VERSION` to 3** so stale `discovery_skips` from the old classifier are invalidated on upgrade.
> 
> Full sync moves **`codex_rollouts_v4` → `codex_rollouts_v5`**, reclassifying cached subagent-marked files without re-reading unchanged roots, and **`RETIRED_SYNC_STATE_KEYS`** ensures legacy Codex rollout state keys are removed from `.sync-state.json` on disk only after the v5 successor is written.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit 2e7deb6a1552babd8764cd78bb84ef5d6720dcd5. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

**Comment by levin7734** [comment]
Addressed Cubic's stale-cache upgrade finding in `9584aa1`.

- introduces `codex_rollouts_v5`
- migrates v4 root stamps onto the fast path unchanged
- invalidates only prior `subagent: true` entries for metadata reclassification
- keeps linked children out of the catalog while promoting a marker-only standalone guardian
- adds an upgrade regression covering the normal-root fast path, standalone guardian, and linked child

Validation: `cargo fmt --all -- --check`, `cargo test -p ai-hist-engine` (200 unit + 19 discovery + 3 resilience tests passed; benchmark ignored), and `git diff --check`.

**Comment by willwashburn** [comment]
hey @levin7734 thanks for the contribution. what are you looking to use this change for? what sparked this PR? happy to help if I can understand the change more

File: crates/ai-hist/src/lib.rs [hunk 1]
```diff
@@ -5317,16 +5319,26 @@ fn sync_codex_rollouts(
...
         .cloned()
         .unwrap_or_default();
+    if !has_v5 && has_v4 {
+        seen.retain(|_, record| record.get("subagent").and_then(Value::as_bool) != Some(true));
+    }
     // Superseded stamp maps from the split-walk era; keeping them would carry
     // three path->stamp maps over the same 2K-file tree in .sync-state.json.
     state.remove("codex_rollouts");
     state.remove("codex_rollout_user_messages_v2");
+    state.remove("codex_rollouts_v4");
```
[the remark this answers is not in the document]
Comment (khaliqgant) [reply crates/ai-hist/src/lib.rs:5470]: Valid, and still applicable after the rebase onto current `main` — fixed in f090579.

You were right about the mechanism: `merged_sync_state` folds *this run's* keys into what is already on disk and never walks the on-disk keys. That is deliberate — a run legitimately omits every source it did not touch, so absence cannot be read as "delete" without destroying the checkpoints of sources this run never looked at. The consequence is exactly as you described: `state.remove("codex_rollouts_v4")` was invisible to disk, so the retired map was reloaded and rewritten on every sync and the cleanup the migration exists to perform never completed.

Fixed by declaring retirements explicitly rather than inferring them from absence — a new `RETIRED_SYNC_STATE_KEYS` list, swept in the merge *after* the fold so a concurrent run still writing one cannot resurrect it.

Scope note: the same silent failure applied to the three sibling removals, not just the v4 key you flagged — `codex_rollouts` and `codex_rollout_user_messages_v2` (removed alongside v4) and `codex_rollouts_v3`. Since the defect is in the merge primitive rather than any one call site, all four are retired together; fixing only v4 would have left the same bug on the other three.

Proof the regression test can see the defect — deleting the sweep and rerunning:

```
test retired_state_keys_are_deleted_from_disk_not_just_from_memory ... FAILED
panicked: codex_rollouts must not survive the migration on disk
```

The test goes through a real `save_sync_state` → `checkpoint_sync_state` → `load_sync_state` round-trip, since the in-memory assertions that already existed could not see this. It also pins the two properties that make the fix safe: a source absent from `ours` (`claude`) is still preserved, and a steady-state run with nothing retired left on disk does not rewrite the file.

`cargo test --workspace` is green.

**Comment by khaliqgant** [comment]
## Ready for review — but please read "Behaviour collision" before merging

Rebased onto current `main` (`0b624ca`, 0.15.2) from a 7-day-old base. Both review threads are closed. The rebase had real conflicts in `crates/ai-hist/src/lib.rs` and one of them is a genuine disagreement with a commit that landed on `main` while this sat, so it needs a human call rather than my judgement.

### Threads

| Thread | Outcome |
| --- | --- |
| cubic-dev-ai `lib.rs:5555` — stale `codex_rollouts_v4` records keep `subagent: true` after upgrade | **Fixed** by `9584aa1` (resolved before this pass); verified still correct after rebase |
| cubic-dev-ai `lib.rs:5341` — `state.remove("codex_rollouts_v4")` is not durable | **Fixed** by `f090579` (new) |

### Behaviour collision — needs your call

`ac0b64a` ("fix: resolve Codex subagent parent IDs", Will, Sep 1) landed on `main` the same day as this PR's commits and added:

```rust
fn codex_marker_only_guardian_remains_an_unlinked_subagent() {
    assert!(meta.is_subagent);
    assert_eq!(meta.parent_session_id, None);
}
```

That asserts the exact behaviour this PR exists to change: a marker-only guardian (`source.subagent`, no parent) staying classified as a subagent, which means `discover` returns `None` for it and it never gets a catalog row.

I resolved it **in this PR's favour** and retargeted the test, because that commit's own subject was parent *resolution*, and its substantive assertion — a marker-only rollout resolves no parent — is preserved unchanged. The `is_subagent` line looks like it was documenting the then-current classification rather than defending it. The test is now `codex_marker_only_guardian_is_a_standalone_root`, plus a new sibling `codex_marker_guardian_with_a_parent_stays_a_subagent` covering the linked case that `ac0b64a` was protecting.

If Will intended that classification deliberately, this PR's premise is wrong and it should be closed instead of merged. **One assertion is the whole disagreement**, so it is cheap to reverse either way. Worth a word with him before the merge.

### Conflict resolution worth reviewing

`main` had evolved `codex_parent_thread_id` / `codex_parent_session_id` to also resolve a parent nested at `source.subagent.thread_spawn.parent_thread_id`. This PR had independently added its own simpler `codex_parent_session_id` that only reads the two top-level fields, and the auto-merge left **both** definitions in the file.

I dropped this PR's copy and kept `main`'s, with `codex_is_subagent` (this PR's actual contribution) now deferring to it. That matters for correctness, not just tidiness: with this PR's original resolver, a guardian whose parent is reachable *only* through `thread_spawn` would have resolved no parent, been classified standalone, and been wrongly cataloged as a root session. The new `codex_marker_guardian_with_a_parent_stays_a_subagent` test pins both shapes.

### `f090579` — the durability fix

`merged_sync_state` folds this run's keys into what is on disk and never walks the on-disk keys, deliberately: a run legitimately omits sources it did not touch, so absence cannot mean "delete". So `state.remove(...)` never reached disk and the retired maps were reloaded and rewritten forever. Retirements are now declared in `RETIRED_SYNC_STATE_KEYS` and swept in the merge after the fold.

Scoped past the reported key on purpose — `codex_rollouts`, `codex_rollout_user_messages_v2` and `codex_rollouts_v3` had the identical silent failure, and the defect is in the merge primitive rather than any one call site.

### Verification

Both new regression tests were proven to see their defect — reintroduced it, watched the test fail, restored the fix (output in the thread replies). `cargo fmt --check`, `cargo clippy --workspace --all-targets -D warnings` and `cargo test --workspace` are green locally (279 lib + 19 discovery + 3 resilience + 123 core).

One caveat on the check rollup: cubic reports `skipping` and CodeRabbit `Review rate limited` on this PR, so neither bot has actually re-reviewed the rebased code — the green ticks there do not mean much.

Not merging — merge gate is yours.

File: crates/ai-hist/src/discover.rs [hunk 2]
```diff
@@ -868,16 +868,10 @@ impl ShallowSessionProvider for CodexProvider {
         else {
             return Ok(None);
         };
-        // Subagent threads are real rollouts but not user sessions; the full
-        // sync excludes them from `sessions` and so does discovery.
-        let is_subagent = payload
-            .and_then(|p| p.get("thread_source"))
-            .and_then(Value::as_str)
-            == Some("subagent")
```
[the remark this answers is not in the document]
Comment (khaliqgant) [reply crates/ai-hist/src/discover.rs:876]: Confirmed and fixed in 2e7deb6 — good catch, this was the difference between the PR working on a fresh catalog and working for anyone who has already run discovery.

`is_known_non_session` compares the stored `discovery_skips.stamp` against `stored_stamp(raw)` = `v{SHALLOW_SCANNER_VERSION}:{raw}` by exact equality. A guardian that an earlier run classified as a subagent was recorded there, and guardian rollouts do not change on disk, so with the version pinned at 2 the stamp kept matching and the file was never re-read under the new predicate. Existing catalogs would have stayed exactly as broken as before the PR.

This is the same class as the `codex_rollouts_v4` cache finding cubic raised on the sync side — the classification changed under two caches, and only one of them was invalidated.

Fixed by bumping `SHALLOW_SCANNER_VERSION` to 3, which is precisely what that constant documents itself as being for ("a scanner that learns to extract a new field re-reads sources whose bytes never changed").

Two things guard it now:

- `an_upgrade_re_reads_a_guardian_an_older_scanner_skipped` seeds a skip at the previous version with this fixture's *real* raw stamp, so the seeded row differs from a live one only by its version prefix. It first asserts a current-version skip does suppress the read (the control), then that the older-version one does not.
- A compile-time guard next to the constant, `const _: () = assert!(SHALLOW_SCANNER_VERSION > 2);`, because the runtime test is written relative to whatever the current version is and therefore cannot see the bump itself. Reverting the bump now fails the build:

```
error[E0080]: evaluation panicked: assertion failed: SHALLOW_SCANNER_VERSION > 2
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `discover::_` failed here
```

Cost is a one-time full shallow re-read on upgrade, which is the documented price of a bump.

File: crates/ai-hist/src/lib.rs [hunk 3]
```diff
@@ -4671,6 +4690,13 @@ fn merged_sync_state(path: &Path, ours: &Map<String, Value>) -> Result<Option<Ma
         merged.insert(key.clone(), next);
         changed = true;
     }
+    // Runs concurrent with this one may still be writing a retired key, so sweep
+    // after the fold rather than before it.
+    for key in RETIRED_SYNC_STATE_KEYS {
+        if merged.remove(*key).is_some() {
+            changed = true;
+        }
+    }
```
[the remark this answers is not in the document]
Comment (khaliqgant) [reply crates/ai-hist/src/lib.rs:4709]: Correct, and this one was mine — introduced in f090579 earlier today. Fixed in 2e7deb6.

I had listed `codex_rollouts_v4` in `RETIRED_SYNC_STATE_KEYS` while this version still reads it (`state.get("codex_rollouts_v5").or_else(|| state.get("codex_rollouts_v4"))`, plus the `has_v4` reclassification), which violates the "only list keys no supported version still reads" rule I wrote in that same doc comment. Since `checkpoint_sync_state` runs once per source against the whole state map, an earlier source's checkpoint deleted v4 from disk before `sync_codex_rollouts` had written v5, exactly as you describe. The in-memory map still had v4 so a clean run was fine — the exposure is a crash or an overlapping sync inside that window, which would then find neither map and force the full archive re-read and the user-message repair path.

Rather than drop v4 from the list (which would have un-fixed the durability issue cubic reported), retired keys are now paired with the key that supersedes them:

```rust
const RETIRED_SYNC_STATE_KEYS: &[(&str, &str)] = &[
    ("codex_rollouts", "codex_rollouts_v5"),
    ("codex_rollout_user_messages_v2", "codex_rollouts_v5"),
    ("codex_rollouts_v3", "codex_rollouts_v5"),
    ("codex_rollouts_v4", "codex_rollouts_v5"),
];
```

and the sweep skips a retirement unless the successor is in the same write. The old map only leaves disk once its replacement is on the way there. `sync_codex_rollouts` writes v5 unconditionally on success, so the migration still completes in the run that performs it — just not before it.

New regression test `a_retired_key_survives_until_its_successor_is_written` checkpoints an earlier source first and asserts v4 is still readable, then checkpoints again with v5 present and asserts it is gone. Removing the guard makes it fail on the first assertion.

`cargo test --workspace` is green (281 lib + 19 discovery + 3 resilience + 123 core), as are `cargo fmt --check` and `cargo clippy --workspace --all-targets -D warnings`.

**Comment by khaliqgant** [comment]
## Update — two more findings fixed, `2e7deb6`

Cursor Bugbot re-reviewed after the rebase push and found two real defects. Both are fixed and both threads are closed; Bugbot has since re-run on `2e7deb6` and passes, and all three CI jobs are green.

**1. Stale discovery skips hid the guardians (High).** This one mattered: the PR worked on a fresh catalog and would have done nothing for any existing install. A guardian an older scanner classified as a subagent is remembered in `discovery_skips`, matched by exact equality against `v{SHALLOW_SCANNER_VERSION}:{raw}`. Guardian rollouts do not change on disk, so with the version still at `2` the stamp kept matching, the file was never re-read under the new predicate, and the original `SESSION_NOT_FOUND` symptom survived untouched. Bumped to `3`.

This is the same root cause as the `codex_rollouts_v4` finding cubic raised — the classification changed under **two** caches (the sync stamp map and the discovery skip table), in two different files with two different invalidation mechanisms, and only the first had been handled.

**2. `codex_rollouts_v4` retired before its successor was written (Medium).** Mine, introduced in `f090579` earlier today. I listed v4 as retired while this version still reads it to seed the v5 migration — violating the "only list keys no supported version still reads" rule in my own doc comment on that constant. Retired keys are now paired with the key that supersedes them and swept only in a write that carries it.

### Note on the version bump

The runtime test for #1 is written relative to whatever `SHALLOW_SCANNER_VERSION` currently is, so it verifies the invalidation *mechanism* but cannot see whether the bump actually happened — it passed with the version reverted to `2`. That gap is covered by a compile-time guard next to the constant instead:

```rust
const _: () = assert!(SHALLOW_SCANNER_VERSION > 2);
```

Reverting the bump now fails the build rather than passing a green suite. Cost of the bump is a one-time full shallow re-read on upgrade, which is the documented price.

Everything in the previous comment still stands, including the **behaviour collision with `ac0b64a`** that needs a human call before merge.
